import { container } from "@/config/container";
import { authenticate, authorization } from "@/shared/middleware/auth.middleware";
import { AuthRouter } from "@/modules/auth/auth.route";
import { AUTH_TYPES } from "@/modules/auth/auth.types";
import { ATTRIBUTE_TYPES, AttributeRouter } from "@/modules/attribute";
import { FILE_TYPES, FileRouter } from "@/modules/file";
import { ROLE_TYPES, RoleRouter } from "@/modules/role";
import { USER_TYPES, UserRouter } from "@/modules/user";
import { getCode } from "@/shared/utils/code.utils";
import { Router } from "express";
import { LOG_TYPES, LogRouter } from "@/modules/log";
import { BOOKING_TYPES, BookingRouter } from "@/modules/booking";
import { CHECK_IN_TYPES, CheckInRouter } from "@/modules/checkIn";
import { CLUB_TYPES, ClubRouter } from "@/modules/club";
import { CLUB_ACTIVITY_TYPES, ClubActivityRouter } from "@/modules/clubActivity";
import { CLUB_MEMBER_TYPES, ClubMemberRouter } from "@/modules/clubMember";
import { CLUB_ROLE_TYPES, ClubRoleRouter } from "@/modules/clubRole";
import { HEALTH_INDICATOR_TYPES, HealthIndicatorRouter } from "@/modules/healthIndicator";
import { PACKET_TYPES, PacketRouter } from "@/modules/packet";
import { USER_PACKET_TYPES, UserPacketRouter } from "@/modules/userPacket";
import { USER_TARGET_TYPES, UserTargetRouter } from "@/modules/userTarget";
import { DASHBOARD_TYPES, DashboardRouter } from "@/modules/dashboard";
import { GOONG_MAP_TYPES } from "@/modules/goongMap/goongMap.types";
import { GoongMapRouter } from "@/modules/goongMap/goongMap.route";
import { CHAT_TYPES, ChatRouter } from "@/modules/chat";
import { SEEN_MESSAGE_TYPES, SeenMessageRouter } from "@/modules/seenMessage";
import customerRouter from "./user.route";
import managerRouter from "./manager.route";

const router = Router();
const authRouter = container.get<AuthRouter>(AUTH_TYPES.AuthRouter);
const attributeRouter = container.get<AttributeRouter>(ATTRIBUTE_TYPES.AttributeRouter);
const userRouter = container.get<UserRouter>(USER_TYPES.UserRouter);
const fileRouter = container.get<FileRouter>(FILE_TYPES.FileRouter);
const roleRouter = container.get<RoleRouter>(ROLE_TYPES.RoleRouter);
const logRouter = container.get<LogRouter>(LOG_TYPES.LogRouter);
const bookingRouter = container.get<BookingRouter>(BOOKING_TYPES.BookingRouter);
const checkInRouter = container.get<CheckInRouter>(CHECK_IN_TYPES.CheckInRouter);
const clubRouter = container.get<ClubRouter>(CLUB_TYPES.ClubRouter);
const clubActivityRouter = container.get<ClubActivityRouter>(CLUB_ACTIVITY_TYPES.ClubActivityRouter);
const clubMemberRouter = container.get<ClubMemberRouter>(CLUB_MEMBER_TYPES.ClubMemberRouter);
const clubRoleRouter = container.get<ClubRoleRouter>(CLUB_ROLE_TYPES.ClubRoleRouter);
const healthIndicatorRouter = container.get<HealthIndicatorRouter>(HEALTH_INDICATOR_TYPES.HealthIndicatorRouter);
const packetRouter = container.get<PacketRouter>(PACKET_TYPES.PacketRouter);
const userPacketRouter = container.get<UserPacketRouter>(USER_PACKET_TYPES.UserPacketRouter);
const userTargetRouter = container.get<UserTargetRouter>(USER_TARGET_TYPES.UserTargetRouter);
const dashboardRouter = container.get<DashboardRouter>(DASHBOARD_TYPES.DashboardRouter);
const goongMapRouter = container.get<GoongMapRouter>(GOONG_MAP_TYPES.GoongMapRouter);
const chatRouter = container.get<ChatRouter>(CHAT_TYPES.ChatRouter);
const seenMessageRouter = container.get<SeenMessageRouter>(SEEN_MESSAGE_TYPES.SeenMessageRouter);

router.use("/auth", authRouter.getRouter());

router.use(authenticate);
router.use(authorization);
router.use("/customer", customerRouter);
router.use("/manager", managerRouter);
router.use("/attribute", attributeRouter.getRouter());
router.use("/user", userRouter.getRouter());
router.use("/file", fileRouter.getRouter());
router.use("/role", roleRouter.getRouter());
router.use("/log", logRouter.getRouter());
router.use("/booking", bookingRouter.getRouter());
router.use("/check-in", checkInRouter.getRouter());
router.use("/club", clubRouter.getRouter());
router.use("/club-activity", clubActivityRouter.getRouter());
router.use("/club-member", clubMemberRouter.getRouter());
router.use("/club-role", clubRoleRouter.getRouter());
router.use("/health-indicator", healthIndicatorRouter.getRouter());
router.use("/packet", packetRouter.getRouter());
router.use("/user-packet", userPacketRouter.getRouter());
router.use("/user-target", userTargetRouter.getRouter());
router.use("/dashboard", dashboardRouter.getRouter());
router.use("/goong-map", goongMapRouter.getRouter());
router.use("/chat", chatRouter.getRouter());
router.use("/seen-message", seenMessageRouter.getRouter());
router.use("/code", getCode);

export default router;
